name: Test to Modal Build

on:
  push:
    branches:
      - dev
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
    paths:
      - "apps/docs/**"

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: "7.15.0"

      - name: Build workspace
        run: |
          pnpm install
          cd packages/modal
          pnpm build
